@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        class com.example.ocp.demoocpchocolatemanager.model.Chocolate {
            - description : String
            + Chocolate()
            {static} + builder()
            + equals()
            + getDescription()
            + hashCode()
            + setDescription()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        class com.example.ocp.demoocpchocolatemanager.model.Chocolate.ChocolateBuilder {
            - description : String
            + build()
            + description()
            + toString()
            ~ ChocolateBuilder()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        enum ChocolateCategory {
          BASIC
          PREMIUM
          identifier
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        enum ChocolateSelection {
          COCOA_CHOCOLATE
          DARK_CHOCOLATE
          MILK_CHOCOLATE
          WHITE_CHOCOLATE
        }
      }
    }
  }
  

  com.example.ocp.demoocpchocolatemanager.model.Chocolate +-down- com.example.ocp.demoocpchocolatemanager.model.Chocolate.ChocolateBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
