@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace om.example.srp.demoSRPGameManager {
      namespace model {
        class com.example.srp.demosrpgamemanager.model.ActionPlayer {
            - action : String
            + ActionPlayer()
            + ActionPlayer()
            + equals()
            + getAction()
            + hashCode()
            + setAction()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.srp.demoSRPGameManager {
      namespace model {
        class com.example.srp.demosrpgamemanager.model.Player {
            - highScore : long
            - id : String
            - name : String
            + Player()
            + Player()
            {static} + builder()
            + equals()
            + getActionPlayer()
            + getHighScore()
            + getId()
            + getName()
            + getSessionPlayer()
            + hashCode()
            + setActionPlayer()
            + setHighScore()
            + setId()
            + setName()
            + setSessionPlayer()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.srp.demoSRPGameManager {
      namespace model {
        class com.example.srp.demosrpgamemanager.model.Player.PlayerBuilder {
            - highScore : long
            - id : String
            - name : String
            + actionPlayer()
            + build()
            + highScore()
            + id()
            + name()
            + sessionPlayer()
            + toString()
            ~ PlayerBuilder()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.srp.demoSRPGameManager {
      namespace model {
        class com.example.srp.demosrpgamemanager.model.SessionPlayer {
            - sessionId : String
            + SessionPlayer()
            + SessionPlayer()
            + equals()
            + getSessionId()
            + hashCode()
            + setSessionId()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  com.example.srp.demosrpgamemanager.model.Player o-- com.example.srp.demosrpgamemanager.model.ActionPlayer : actionPlayer
  com.example.srp.demosrpgamemanager.model.Player o-- com.example.srp.demosrpgamemanager.model.SessionPlayer : sessionPlayer
  com.example.srp.demosrpgamemanager.model.Player +-down- com.example.srp.demosrpgamemanager.model.Player.PlayerBuilder
  com.example.srp.demosrpgamemanager.model.Player.PlayerBuilder o-- com.example.srp.demosrpgamemanager.model.ActionPlayer : actionPlayer
  com.example.srp.demosrpgamemanager.model.Player.PlayerBuilder o-- com.example.srp.demosrpgamemanager.model.SessionPlayer : sessionPlayer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
