@startuml

title __FACTORIES's Class Diagram__\n

  namespace com.example.dip.demodippizzamanager {
    namespace factories {
      class com.example.dip.demodippizzamanager.factories.ChicagoPizzaIngredientFactory {
          + createCheese()
          + createClam()
          + createDough()
          + createPepperoni()
          + createSauce()
          + createVeggies()
      }
    }
  }
  

  namespace com.example.dip.demodippizzamanager {
    namespace factories {
      class com.example.dip.demodippizzamanager.factories.NYPizzaIngredientFactory {
          + createCheese()
          + createClam()
          + createDough()
          + createPepperoni()
          + createSauce()
          + createVeggies()
      }
    }
  }
  

  namespace com.example.dip.demodippizzamanager {
    namespace factories {
      interface com.example.dip.demodippizzamanager.factories.PizzaIngredientFactory {
          {abstract} + createCheese()
          {abstract} + createClam()
          {abstract} + createDough()
          {abstract} + createPepperoni()
          {abstract} + createSauce()
          {abstract} + createVeggies()
      }
    }
  }
  

  com.example.dip.demodippizzamanager.factories.ChicagoPizzaIngredientFactory .up.|> com.example.dip.demodippizzamanager.factories.PizzaIngredientFactory
  com.example.dip.demodippizzamanager.factories.NYPizzaIngredientFactory .up.|> com.example.dip.demodippizzamanager.factories.PizzaIngredientFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
