@startuml
title __DEMOOCPCHOCOLATEMANAGER's Class Diagram__\n


    class MavenWrapperDownloader {
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      class com.example.ocp.demoOCPChocolateManager.DemoOCPChocolateManagerApplication {
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace config {
        class com.example.ocp.demoOCPChocolateManager.config.SwaggerConfigurator {
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace machine {
        class com.example.ocp.demoOCPChocolateManager.machine.BasicChocolateMachine {
		  + brewChocolate()
            + brewMilkChocolate()
            + brewWhiteChocolate()
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace machine {
        interface com.example.ocp.demoOCPChocolateManager.machine.ChocolateMachine {
		{abstract} + brewChocolate()
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace machine {
        class com.example.ocp.demoOCPChocolateManager.machine.PremiumChocolateMachine {
		+ brewChocolate()
            + brewCocoaChocolate()
            + brewDarkChocolate()
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace manager {
        class com.example.ocp.demoOCPChocolateManager.manager.ChocolateManager {
		   {static} - SERVICE_NAME_SUFFIX : String
            - beanFactory : BeanFactory
            + brewChocolate()

        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        class com.example.ocp.demoOCPChocolateManager.model.Chocolate {
		- description : String
		+ getDescription()
		+ setDescription()
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        enum ChocolateCategory {
		BASIC
          PREMIUM
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace model {
        enum ChocolateSelection {
		COCOA_CHOCOLATE
          DARK_CHOCOLATE
          MILK_CHOCOLATE
          WHITE_CHOCOLATE
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace resource {
        class com.example.ocp.demoOCPChocolateManager.resource.ChocolateRequest {
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace resource {
        class com.example.ocp.demoOCPChocolateManager.resource.ChocolateResponse {
        }
      }
    }




    namespace om.example.ocp.demoOCPChocolateManager {
      namespace webservice {
        class com.example.ocp.demoOCPChocolateManager.webservice.ChocolateController {
		+ brewChocolate()
        }
      }
    }



  com.example.ocp.demoOCPChocolateManager.machine.BasicChocolateMachine .up.|> com.example.ocp.demoOCPChocolateManager.machine.ChocolateMachine
  com.example.ocp.demoOCPChocolateManager.machine.PremiumChocolateMachine .up.|> com.example.ocp.demoOCPChocolateManager.machine.ChocolateMachine
  com.example.ocp.demoOCPChocolateManager.manager.ChocolateManager o-- com.example.ocp.demoOCPChocolateManager.machine.ChocolateMachine : chocolateMachine
  com.example.ocp.demoOCPChocolateManager.resource.ChocolateRequest o-- com.example.ocp.demoOCPChocolateManager.model.ChocolateCategory : chocolateCategory
  com.example.ocp.demoOCPChocolateManager.resource.ChocolateRequest o-- com.example.ocp.demoOCPChocolateManager.model.ChocolateSelection : chocolateSelection
  com.example.ocp.demoOCPChocolateManager.resource.ChocolateResponse o-- com.example.ocp.demoOCPChocolateManager.model.Chocolate : chocolate
  com.example.ocp.demoOCPChocolateManager.webservice.ChocolateController o-- com.example.ocp.demoOCPChocolateManager.manager.ChocolateManager : chocolateManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter
@enduml